# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH']= "../platforms" 
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1096, 698)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(430, 60, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plainText = QtWidgets.QPlainTextEdit(Dialog)
        self.plainText.setGeometry(QtCore.QRect(110, 130, 281, 91))
        self.plainText.setObjectName("plainText")
        self.generatekeys = QtWidgets.QPushButton(Dialog)
        self.generatekeys.setGeometry(QtCore.QRect(660, 70, 91, 23))
        self.generatekeys.setObjectName("generatekeys")
        self.plain = QtWidgets.QLabel(Dialog)
        self.plain.setGeometry(QtCore.QRect(50, 130, 51, 16))
        self.plain.setObjectName("plain")
        self.ciphertext = QtWidgets.QPlainTextEdit(Dialog)
        self.ciphertext.setGeometry(QtCore.QRect(110, 300, 281, 91))
        self.ciphertext.setObjectName("ciphertext")
        self.cipher = QtWidgets.QLabel(Dialog)
        self.cipher.setGeometry(QtCore.QRect(40, 300, 61, 20))
        self.cipher.setObjectName("cipher")
        self.information = QtWidgets.QLabel(Dialog)
        self.information.setGeometry(QtCore.QRect(536, 123, 71, 20))
        self.information.setObjectName("information")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(550, 300, 47, 13))
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(630, 130, 281, 91))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(630, 300, 281, 91))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.encrypt = QtWidgets.QPushButton(Dialog)
        self.encrypt.setGeometry(QtCore.QRect(100, 450, 75, 23))
        self.encrypt.setObjectName("encrypt")
        self.decrypt = QtWidgets.QPushButton(Dialog)
        self.decrypt.setGeometry(QtCore.QRect(360, 450, 75, 23))
        self.decrypt.setObjectName("decrypt")
        self.sign = QtWidgets.QPushButton(Dialog)
        self.sign.setGeometry(QtCore.QRect(590, 450, 75, 23))
        self.sign.setObjectName("sign")
        self.verify = QtWidgets.QPushButton(Dialog)
        self.verify.setGeometry(QtCore.QRect(840, 450, 75, 23))
        self.verify.setObjectName("verify")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "RSA CIPHER"))
        self.generatekeys.setText(_translate("Dialog", "generate Keys"))
        self.plain.setText(_translate("Dialog", "Plain Text"))
        self.cipher.setText(_translate("Dialog", "Cipher Text"))
        self.information.setText(_translate("Dialog", "Informartion"))
        self.label_2.setText(_translate("Dialog", "Signature"))
        self.encrypt.setText(_translate("Dialog", "Encrypt"))
        self.decrypt.setText(_translate("Dialog", "Decrypt"))
        self.sign.setText(_translate("Dialog", "Sign"))
        self.verify.setText(_translate("Dialog", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
